#!/usr/bin/env python3
"""
Visualize Grackle cooling table and compare with RAMSES cooling module.
Reads the binary table generated by grackle_cooling_grid.c
"""
import struct
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, SymLogNorm
import os, sys, re

# ============================================================
# Read Grackle binary table
# ============================================================
def read_grackle_table(filename):
    """Read Grackle binary cooling table."""
    with open(filename, 'rb') as f:
        L, M, N = struct.unpack('iii', f.read(12))
        z_val, log_dmin, log_dmax, log_zmin, log_zmax, log_tmin, log_tmax = \
            struct.unpack('7d', f.read(56))
        log_T = np.array(struct.unpack(f'{N}d', f.read(N*8)))
        total = L * M * N
        net_rate = np.array(struct.unpack(f'{total}d', f.read(total*8)))
        mmw = np.array(struct.unpack(f'{total}d', f.read(total*8)))

    # Reshape: C order (density, metallicity, temperature)
    net_rate = net_rate.reshape(L, M, N)
    mmw = mmw.reshape(L, M, N)

    # Build grids
    density = np.logspace(log_dmin, log_dmax, L)  # nH [cm^-3]
    metallicity = np.logspace(log_zmin, log_zmax, M)  # Z_solar
    temperature = 10.0 ** log_T  # T [K]

    return {
        'L': L, 'M': M, 'N': N,
        'redshift': z_val,
        'density': density, 'metallicity': metallicity, 'temperature': temperature,
        'net_rate': net_rate, 'mmw': mmw,
        'log_T': log_T,
    }

# ============================================================
# Parse RAMSES log for cooling comparison stats
# ============================================================
def parse_cooling_compare_log(logfile):
    """Parse RAMSES log for 'Cooling compare' lines."""
    steps, mean_rdiff, max_rdiff = [], [], []
    dT_orig, dT_exact, sign_pct = [], [], []

    with open(logfile) as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        m = re.search(r'Cooling compare step=\s*(\d+)\s+ncell=\s*(\d+)', line)
        if m:
            step = int(m.group(1))
            ncell = int(m.group(2))
            # Next line: mean_rel_diff and max_rel_diff
            if i+1 < len(lines):
                m2 = re.search(r'mean_rel_diff=\s*([\d.eE+-]+)\s+max_rel_diff=\s*([\d.eE+-]+)', lines[i+1])
                if m2:
                    steps.append(step)
                    mean_rdiff.append(float(m2.group(1)))
                    max_rdiff.append(float(m2.group(2)))
            # Next line: <dT2_original>, <dT2_exact>, sign_mismatch
            if i+2 < len(lines):
                m3 = re.search(r'<dT2_original>=\s*([\d.eE+-]+)\s+<dT2_exact>=\s*([\d.eE+-]+)\s+sign_mismatch=\s*([\d.]+)%', lines[i+2])
                if m3:
                    dT_orig.append(float(m3.group(1)))
                    dT_exact.append(float(m3.group(2)))
                    sign_pct.append(float(m3.group(3)))

    return {
        'steps': np.array(steps),
        'mean_rdiff': np.array(mean_rdiff),
        'max_rdiff': np.array(max_rdiff),
        'dT_orig': np.array(dT_orig),
        'dT_exact': np.array(dT_exact),
        'sign_pct': np.array(sign_pct),
    }

# ============================================================
# Plotting functions
# ============================================================
def plot_cooling_curves(tab, outfile='grackle_cooling_curves.png'):
    """Plot net cooling rate vs temperature at various densities."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    T = tab['temperature']
    Z_idx_solar = np.argmin(np.abs(np.log10(tab['metallicity'])))  # ~1 Z_solar
    Z_idx_low = np.argmin(np.abs(np.log10(tab['metallicity']) + 3))  # ~1e-3 Z_solar

    colors = plt.cm.viridis(np.linspace(0.1, 0.9, 8))
    dens_indices = np.linspace(0, tab['L']-1, 8, dtype=int)

    for ax_idx, (ax, Z_idx, Z_label) in enumerate(zip(axes,
            [Z_idx_solar, Z_idx_low],
            [f'Z = {tab["metallicity"][Z_idx_solar]:.2f} Z$_\\odot$',
             f'Z = {tab["metallicity"][Z_idx_low]:.1e} Z$_\\odot$'])):

        for ci, di in enumerate(dens_indices):
            rate = tab['net_rate'][di, Z_idx, :]  # already erg/cm^3/s
            nH_val = tab['density'][di]

            # Split into cooling (positive) and heating (negative)
            mask_cool = rate > 0
            mask_heat = rate < 0

            label = f'n$_H$ = {nH_val:.0e}'
            if mask_cool.any():
                ax.plot(T[mask_cool], rate[mask_cool], '-', color=colors[ci],
                        label=label, linewidth=1.2)
            if mask_heat.any():
                ax.plot(T[mask_heat], -rate[mask_heat], '--', color=colors[ci],
                        linewidth=0.8, alpha=0.7)

        ax.set_xscale('log')
        ax.set_yscale('log')
        ax.set_xlabel('Temperature [K]', fontsize=12)
        ax.set_ylabel(r'|$\Lambda_{\rm net}$| [erg cm$^{-3}$ s$^{-1}$]', fontsize=12)
        ax.set_title(f'Grackle Net Cooling Rate ({Z_label})', fontsize=12)
        ax.legend(fontsize=7, loc='lower right', ncol=2)
        ax.set_xlim(10, 1e9)
        ax.set_ylim(1e-38, 1e-10)
        ax.grid(True, alpha=0.3)
        ax.text(0.03, 0.97, f'z = {tab["redshift"]:.1f}\nSolid = cooling\nDashed = heating',
                transform=ax.transAxes, fontsize=8, va='top',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout()
    plt.savefig(outfile, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved {outfile}')

def plot_mmw_map(tab, outfile='grackle_mmw_map.png'):
    """Plot mean molecular weight as 2D map (T vs nH) at solar metallicity."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))

    T = tab['temperature']
    nH = tab['density']

    Z_idx = np.argmin(np.abs(np.log10(tab['metallicity'])))

    # mmw map: tab['mmw'] is (L_dens, M_metal, N_temp)
    # [:, Z_idx, :] -> (L_dens, N_temp) = (60, 256) — correct for pcolormesh(T, nH, C)
    mmw_2d = tab['mmw'][:, Z_idx, :]
    im0 = axes[0].pcolormesh(np.log10(T), np.log10(nH), mmw_2d,
                              cmap='RdYlBu_r', vmin=0.55, vmax=1.3, shading='nearest')
    axes[0].set_xlabel('log$_{10}$(T [K])', fontsize=12)
    axes[0].set_ylabel('log$_{10}$(n$_H$ [cm$^{-3}$])', fontsize=12)
    axes[0].set_title(f'Mean Molecular Weight $\\mu$ (Z = {tab["metallicity"][Z_idx]:.2f} Z$_\\odot$)',
                       fontsize=11)
    plt.colorbar(im0, ax=axes[0], label='$\\mu$')

    # net_rate map (sign-preserving): already erg/cm^3/s, (L_dens, N_temp)
    rate_2d = tab['net_rate'][:, Z_idx, :].copy()

    vmax = np.max(np.abs(rate_2d[rate_2d != 0]))
    im1 = axes[1].pcolormesh(np.log10(T), np.log10(nH), rate_2d,
                              cmap='RdBu_r',
                              norm=SymLogNorm(linthresh=1e-30, vmin=-vmax, vmax=vmax),
                              shading='nearest')
    axes[1].set_xlabel('log$_{10}$(T [K])', fontsize=12)
    axes[1].set_ylabel('log$_{10}$(n$_H$ [cm$^{-3}$])', fontsize=12)
    axes[1].set_title(f'Net Rate $\\Lambda$ [erg/cm$^3$/s] (red=cooling, blue=heating)',
                       fontsize=10)
    plt.colorbar(im1, ax=axes[1], label=r'$\Lambda_{\rm net}$')

    for ax in axes:
        ax.set_xlim(1, 9)
        ax.set_ylim(-8, 4)

    plt.tight_layout()
    plt.savefig(outfile, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved {outfile}')

def plot_comparison_stats(stats, outfile='cooling_compare_stats.png'):
    """Plot comparison statistics from RAMSES log."""
    if len(stats['steps']) == 0:
        print('No comparison data found in log.')
        return

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))

    # Mean relative difference
    ax = axes[0, 0]
    ax.semilogy(stats['steps'], stats['mean_rdiff'], 'b.-', linewidth=1, markersize=4)
    ax.set_ylabel('Mean Relative Diff', fontsize=11)
    ax.set_title('|$\\Delta T_2^{\\rm orig}$ - $\\Delta T_2^{\\rm exact}$| / |T2|', fontsize=11)
    ax.grid(True, alpha=0.3)

    # Max relative difference
    ax = axes[0, 1]
    ax.semilogy(stats['steps'], stats['max_rdiff'], 'r.-', linewidth=1, markersize=4)
    ax.set_ylabel('Max Relative Diff', fontsize=11)
    ax.set_title('Max cell-wise relative difference', fontsize=11)
    ax.grid(True, alpha=0.3)

    # Mean dT2 comparison
    ax = axes[1, 0]
    ax.plot(stats['steps'], stats['dT_orig'], 'b.-', label='RAMSES original',
            linewidth=1, markersize=4)
    ax.plot(stats['steps'], stats['dT_exact'], 'r.--', label='Eunha exact',
            linewidth=1, markersize=4)
    ax.set_xlabel('Step', fontsize=11)
    ax.set_ylabel('<$\\Delta T_2$> [K]', fontsize=11)
    ax.set_title('Mean $\\Delta T_2$ per cell', fontsize=11)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # Sign mismatch percentage
    ax = axes[1, 1]
    ax.plot(stats['steps'], stats['sign_pct'], 'g.-', linewidth=1, markersize=4)
    ax.set_xlabel('Step', fontsize=11)
    ax.set_ylabel('Sign Mismatch [%]', fontsize=11)
    ax.set_title('Cells where cooling/heating direction disagrees', fontsize=11)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(bottom=0)

    plt.suptitle('RAMSES solve_cooling vs Eunha exact_integrate Comparison',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(outfile, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved {outfile}')

# ============================================================
# Main
# ============================================================
if __name__ == '__main__':
    basedir = '/gpfs/kjhan/Hydro/CUBE_HR5/code_cube'
    outdir = os.path.join(basedir, 'test_ksection/run_compare_cooling')

    # 1. Grackle table visualization
    table_file = os.path.join(outdir, 'grackle_z5.1.bin')
    if os.path.exists(table_file):
        tab = read_grackle_table(table_file)
        print(f'Grackle table: L={tab["L"]}, M={tab["M"]}, N={tab["N"]}, z={tab["redshift"]:.1f}')

        plot_cooling_curves(tab, os.path.join(outdir, 'grackle_cooling_curves.png'))
        plot_mmw_map(tab, os.path.join(outdir, 'grackle_mmw_map.png'))
    else:
        print(f'Table not found: {table_file}')

    # 2. Comparison statistics from RAMSES log
    import glob
    logs = sorted(glob.glob(os.path.join(outdir, 'cool_cmp_*.log')))
    if logs:
        logfile = logs[-1]
        print(f'Parsing log: {logfile}')
        stats = parse_cooling_compare_log(logfile)
        if len(stats['steps']) > 0:
            plot_comparison_stats(stats, os.path.join(outdir, 'cooling_compare_stats.png'))
        else:
            print('No comparison stats found yet (job may still be running)')
    else:
        print('No log files found yet')
