#!/usr/bin/env python3
"""
mknml.py -- Generate mkpower namelist with preset cosmological parameters.

Usage:
    python3 mknml.py Planck2018              # -> params.nml (Planck 2018)
    python3 mknml.py DESI_w0waCDM -o desi.nml
    python3 mknml.py --list                  # show all presets

Presets:
    WMAP5            WMAP 5-year (Dunkley+ 2009)
    WMAP9            WMAP 9-year (Hinshaw+ 2013)
    Planck2015       Planck 2015 (XIII, TT+lowP+lensing)
    Planck2018       Planck 2018 (VI, TT,TE,EE+lowE+lensing)
    DESI_LCDM        DESI DR1 + CMB, flat LCDM (DESI 2024 VI)
    DESI_w0waCDM     DESI DR1 + CMB + PantheonPlus, w0-wa CPL (DESI 2024 VI)
"""

import sys
import argparse
import textwrap

# ------------------------------------------------------------------ #
#  Cosmology presets
# ------------------------------------------------------------------ #

PRESETS = {
    "WMAP5": {
        "label": "WMAP 5-year (Dunkley+ 2009, WMAP+BAO+SN)",
        "ref":   "arXiv:0803.0586",
        "omega_m":  0.279,
        "omega_b":  0.0462,
        "omega_l":  0.721,
        "h0":       70.5,
        "n_s":      0.963,
        "sigma8":   0.796,
        "tau":      0.087,
        "de_model": "lambda",
    },
    "WMAP9": {
        "label": "WMAP 9-year (Hinshaw+ 2013, WMAP-only, 6-param LCDM)",
        "ref":   "arXiv:1212.5226",
        "omega_m":  0.279,
        "omega_b":  0.0463,
        "omega_l":  0.721,
        "h0":       70.0,
        "n_s":      0.972,
        "sigma8":   0.821,
        "tau":      0.089,
        "de_model": "lambda",
    },
    "Planck2015": {
        "label": "Planck 2015 (XIII, TT+lowP+lensing, 6-param LCDM)",
        "ref":   "arXiv:1502.01589",
        "omega_m":  0.308,
        "omega_b":  0.0484,
        "omega_l":  0.692,
        "h0":       67.8,
        "n_s":      0.968,
        "sigma8":   0.815,
        "tau":      0.066,
        "de_model": "lambda",
    },
    "Planck2018": {
        "label": "Planck 2018 (VI, TT,TE,EE+lowE+lensing, 6-param LCDM)",
        "ref":   "arXiv:1807.06209",
        "omega_m":  0.3153,
        "omega_b":  0.04930,
        "omega_l":  0.6847,
        "h0":       67.36,
        "n_s":      0.9649,
        "sigma8":   0.8111,
        "tau":      0.0544,
        "de_model": "lambda",
    },
    "DESI_LCDM": {
        "label": "DESI DR1 + CMB, flat LCDM (DESI 2024 VI)",
        "ref":   "arXiv:2404.03002",
        "omega_m":  0.3069,
        "omega_b":  0.04880,
        "omega_l":  0.6931,
        "h0":       67.97,
        "n_s":      0.9649,
        "sigma8":   0.8121,
        "tau":      0.0544,
        "de_model": "lambda",
    },
    "DESI_w0waCDM": {
        "label": "DESI DR1 + CMB + PantheonPlus, w0-wa CPL (DESI 2024 VI)",
        "ref":   "arXiv:2404.03002",
        "omega_m":  0.3069,
        "omega_b":  0.04880,
        "omega_l":  0.6931,
        "h0":       67.97,
        "n_s":      0.9649,
        "sigma8":   0.8121,
        "tau":      0.0544,
        "de_model": "ppf",
        "w0":       -0.827,
        "wa":       -0.75,
    },
}

# Aliases for convenience
ALIASES = {
    "wmap5":          "WMAP5",
    "wmap-5":         "WMAP5",
    "wmap_5year":     "WMAP5",
    "wmap9":          "WMAP9",
    "wmap-9":         "WMAP9",
    "wmap_9year":     "WMAP9",
    "planck15":       "Planck2015",
    "planck2015":     "Planck2015",
    "planck-2015":    "Planck2015",
    "planck18":       "Planck2018",
    "planck2018":     "Planck2018",
    "planck-2018":    "Planck2018",
    "planck":         "Planck2018",
    "desi":           "DESI_LCDM",
    "desi_lcdm":      "DESI_LCDM",
    "desi_dr1":       "DESI_LCDM",
    "desi-lcdm":      "DESI_LCDM",
    "desi_w0wacdm":   "DESI_w0waCDM",
    "desi-w0wa":      "DESI_w0waCDM",
    "desi_w0wa":      "DESI_w0waCDM",
    "desi_cpl":       "DESI_w0waCDM",
}


def resolve_preset(name):
    """Resolve preset name (case-insensitive, aliases supported)."""
    key = ALIASES.get(name.lower())
    if key and key in PRESETS:
        return key
    # Try exact match (case-insensitive)
    for k in PRESETS:
        if k.lower() == name.lower():
            return k
    return None


def generate_namelist(preset_name, redshift="0", output_root="camb"):
    """Generate namelist string from preset."""
    p = PRESETS[preset_name]

    de_block = ""
    if p["de_model"] != "lambda":
        de_block = (
            f"\n"
            f"! --- Dark energy model ---\n"
            f"de_model  = '{p['de_model']}'\n"
            f"w0        = {p.get('w0', -1.0)}\n"
            f"wa        = {p.get('wa', 0.0)}\n"
        )

    nml = (
        f"! ============================================================\n"
        f"! mkpower namelist -- {p['label']}\n"
        f"! Reference: {p['ref']}\n"
        f"! Generated by mknml.py\n"
        f"! ============================================================\n"
        f"\n"
        f"&COSMO_PARAMS\n"
        f"\n"
        f"! --- Core cosmological parameters ---\n"
        f"omega_m   = {p['omega_m']}\n"
        f"omega_b   = {p['omega_b']}\n"
        f"omega_l   = {p['omega_l']}\n"
        f"h0        = {p['h0']}\n"
        f"\n"
        f"! --- Primordial power spectrum ---\n"
        f"n_s       = {p['n_s']}\n"
        f"sigma8    = {p['sigma8']}\n"
        f"\n"
        f"! --- CMB, reionization ---\n"
        f"tau       = {p['tau']}\n"
        f"{de_block}"
        f"\n"
        f"! --- Redshift(s) for output ---\n"
        f"redshift  = '{redshift}'\n"
        f"\n"
        f"! --- Output ---\n"
        f"output_root = '{output_root}'\n"
        f"\n"
        f"/\n"
    )
    return nml


def list_presets():
    """Print all available presets."""
    print("Available cosmology presets:")
    print()
    fmt = "  {:<18s}  {:s}"
    for name, p in PRESETS.items():
        print(fmt.format(name, p["label"]))
        vals = (f"Om={p['omega_m']}, Ob={p['omega_b']}, "
                f"h={p['h0']/100:.4f}, s8={p['sigma8']}, ns={p['n_s']}")
        if p["de_model"] != "lambda":
            vals += f", w0={p.get('w0',-1)}, wa={p.get('wa',0)}"
        print(fmt.format("", vals))
        print(fmt.format("", f"[{p['ref']}]"))
        print()
    print("Aliases:")
    by_target = {}
    for alias, target in sorted(ALIASES.items()):
        by_target.setdefault(target, []).append(alias)
    for target, aliases in by_target.items():
        print(f"  {target}: {', '.join(aliases)}")


def main():
    ap = argparse.ArgumentParser(
        description="Generate mkpower namelist from cosmology preset")
    ap.add_argument("preset", nargs="?",
                    help="Cosmology preset name (e.g. Planck2018, WMAP5)")
    ap.add_argument("-o", "--output", default="params.nml",
                    help="Output filename (default: params.nml)")
    ap.add_argument("-z", "--redshift", default="0",
                    help="Redshift(s), space-separated (default: '0')")
    ap.add_argument("-r", "--root", default="camb",
                    help="Output root for mkpower (default: 'camb')")
    ap.add_argument("--list", action="store_true",
                    help="List all available presets")
    args = ap.parse_args()

    if args.list or args.preset is None:
        list_presets()
        if args.preset is None and not args.list:
            print("\nUsage: mknml.py <preset> [-o output.nml] [-z '0 1 10']")
        sys.exit(0)

    key = resolve_preset(args.preset)
    if key is None:
        print(f"Error: unknown preset '{args.preset}'")
        print("Use --list to see available presets")
        sys.exit(1)

    nml = generate_namelist(key, redshift=args.redshift, output_root=args.root)

    with open(args.output, 'w') as f:
        f.write(nml)

    p = PRESETS[key]
    print(f"Wrote {args.output}  [{p['label']}]")
    print(f"  Om={p['omega_m']}, Ob={p['omega_b']}, h={p['h0']/100:.4f}, "
          f"s8={p['sigma8']}, ns={p['n_s']}, tau={p['tau']}")
    if p["de_model"] != "lambda":
        print(f"  de_model={p['de_model']}, w0={p.get('w0',-1)}, wa={p.get('wa',0)}")
    print(f"\nRun: python3 mkpower.py {args.output}")


if __name__ == "__main__":
    main()
