#!/usr/bin/env python3
"""
mkpower.py -- Generate CAMB transfer functions and power spectra in
              standard CAMB ASCII format (compatible with MUSIC).

Reads cosmological parameters from a Fortran-style namelist and outputs:
  <root>_transfer_out.dat   (or per-z: <root>_transfer_out_z<NNN>.dat)
  <root>_matterpower.dat    (or per-z: <root>_matterpower_z<NNN>.dat)

Usage:
    python3 mkpower.py params.nml
    python3 mkpower.py params.nml -r test

Namelist group &COSMO_PARAMS:
    omega_m    : total matter density (CDM + baryon + neutrino)
    omega_b    : baryon density
    omega_l    : dark energy density
    omega_k    : curvature (auto-computed if omitted: 1 - Om - OL)
    omega_nu   : massive neutrino density (default 0)
    h0         : H0 [km/s/Mpc] (or h if <= 10)
    n_s        : scalar spectral index (default 0.9649)
    sigma8     : amplitude sigma_8 at z=0 (default 0.8111)
    A_s        : scalar amplitude (overrides sigma8 if set)
    T_cmb      : CMB temperature [K] (default 2.7255)
    tau        : optical depth to reionization (default 0.0544)
    redshift   : single or space-separated list (default '0')

    de_model   : dark energy model (default 'lambda')
                   'lambda'  — cosmological constant (w=-1 fixed)
                   'fluid'   — w0-wa CPL, constant c_s^2 (quintessence-like)
                   'ppf'     — w0-wa CPL, PPF approximation (allows w-crossing)
                   'axion'   — AxionEffectiveFluid (early dark energy)
    w0         : DE equation of state w0 (default -1, used for fluid/ppf)
    wa         : DE equation of state wa (default 0, used for fluid/ppf)
    cs2_de     : DE sound speed squared (default 1, used for fluid)
    # AxionEffectiveFluid parameters (de_model='axion'):
    axion_fde_zc  : fractional DE density at z_c (default 0.1)
    axion_zc      : critical redshift (default 3000)
    axion_w_n     : effective EOS power (default 1)
    axion_theta_i : initial field angle (default 1)

    output_root : output filename root (default 'camb')

Transfer function output: 13-column CAMB format (MUSIC-compatible)
    k/h  T_cdm  T_b  T_gamma  T_nu  T_mass_nu  T_tot  T_nonu
    T_tot_de  Weyl  v_Newt_cdm  v_Newt_b  v_b+c

Matter power output: 7-column format
    k/h  P_tot  P_cdm  P_b  P_cb  P_cdm_b  P_Weyl

Requires: camb (pip install camb)
"""

import sys
import os
import re
import argparse
import numpy as np

try:
    import camb
    from camb import model, dark_energy
except ImportError:
    print("Error: CAMB not found. Install with: pip install camb")
    sys.exit(1)


# ------------------------------------------------------------------ #
#  Namelist parser
# ------------------------------------------------------------------ #

def parse_namelist(filename, group="COSMO_PARAMS"):
    """Parse a Fortran namelist file, extracting key=value from &group."""
    with open(filename, 'r') as f:
        text = f.read()
    # Strip comments first (avoid '/' inside comments matching terminator)
    text_nocomment = re.sub(r'!.*', '', text)
    pattern = rf'&{group}\s*(.*?)/'
    match = re.search(pattern, text_nocomment, re.IGNORECASE | re.DOTALL)
    if not match:
        print(f"Error: namelist group &{group} not found in {filename}")
        sys.exit(1)
    body = match.group(1)
    body = body.replace('\n', ' ').replace(',', ' ')  # flatten
    params = {}
    for m in re.finditer(r'(\w+)\s*=\s*([^=]+?)(?=\s+\w+\s*=|$)', body):
        params[m.group(1).strip().lower()] = m.group(2).strip()
    return params


def pval(val_str, default, dtype=float):
    """Parse namelist value with Fortran D-exponent and .true./.false."""
    if val_str is None:
        return default
    s = val_str.strip().strip("'\"")
    if dtype == bool:
        return s.lower() in ('.true.', 'true', 't', '1', '.t.')
    if dtype == str:
        return s
    s = re.sub(r'[dD]', 'e', s)  # Fortran D-exponent → e (numeric only)
    return dtype(s)


def parse_redshift_list(val_str, default="0"):
    """Parse redshift(s): single number or space/comma-separated list."""
    if val_str is None:
        val_str = default
    s = val_str.strip().strip("'\"")
    s = re.sub(r'[dD]', 'e', s)
    tokens = re.split(r'[\s,]+', s)
    return sorted([float(t) for t in tokens if t], reverse=True)


# ------------------------------------------------------------------ #
#  File writers (standard CAMB ASCII format)
# ------------------------------------------------------------------ #

def make_transfer_header(z, cosmo_info):
    """Build header lines for transfer function file."""
    lines = []
    lines.append(f"# Transfer functions at z = {z:g}")
    lines.append(f"# Generated by mkpower.py using CAMB {camb.__version__}")
    lines.append(f"# Omega_m = {cosmo_info['omega_m']}  Omega_b = {cosmo_info['omega_b']}"
                 f"  Omega_L = {cosmo_info['omega_l']}  h = {cosmo_info['h']}")
    lines.append(f"# n_s = {cosmo_info['n_s']}  sigma8 = {cosmo_info['sigma8']}")
    if cosmo_info.get('de_model', 'lambda') not in ('lambda', ''):
        lines.append(f"# de_model = {cosmo_info['de_model']}"
                     f"  w0 = {cosmo_info.get('w0', -1)}  wa = {cosmo_info.get('wa', 0)}")
    lines.append(f"# Number of rows: {cosmo_info['nk']}")
    lines.append(f"# Column  1: k/h [Mpc^-1]")
    lines.append(f"# Column  2: T_CDM")
    lines.append(f"# Column  3: T_b")
    lines.append(f"# Column  4: T_gamma")
    lines.append(f"# Column  5: T_nu (massless)")
    lines.append(f"# Column  6: T_massive_nu")
    lines.append(f"# Column  7: T_tot")
    lines.append(f"# Column  8: T_nonu")
    lines.append(f"# Column  9: T_tot_de")
    lines.append(f"# Column 10: Weyl")
    lines.append(f"# Column 11: v_Newt_CDM")
    lines.append(f"# Column 12: v_Newt_b")
    lines.append(f"# Column 13: v_b+c")
    return "\n".join(lines) + "\n"


def make_pk_header(z, cosmo_info):
    """Build header lines for matter power spectrum file."""
    lines = []
    lines.append(f"# Matter power spectra P(k) at z = {z:g}  [(Mpc/h)^3]")
    lines.append(f"# Generated by mkpower.py using CAMB {camb.__version__}")
    lines.append(f"# Omega_m = {cosmo_info['omega_m']}  Omega_b = {cosmo_info['omega_b']}"
                 f"  Omega_L = {cosmo_info['omega_l']}  h = {cosmo_info['h']}")
    lines.append(f"# n_s = {cosmo_info['n_s']}  sigma8 = {cosmo_info['sigma8']}")
    if cosmo_info.get('de_model', 'lambda') not in ('lambda', ''):
        lines.append(f"# de_model = {cosmo_info['de_model']}"
                     f"  w0 = {cosmo_info.get('w0', -1)}  wa = {cosmo_info.get('wa', 0)}")
    lines.append(f"# Number of rows: {cosmo_info['nk_pk']}")
    lines.append(f"# Column 1: k/h [Mpc^-1]")
    lines.append(f"# Column 2: P_tot       (total matter)")
    lines.append(f"# Column 3: P_cdm       (CDM)")
    lines.append(f"# Column 4: P_b         (baryon)")
    lines.append(f"# Column 5: P_cb        (CDM+baryon, 'nonu')")
    lines.append(f"# Column 6: P_cdm_b     (CDM x baryon cross)")
    lines.append(f"# Column 7: P_Weyl      (Weyl potential)")
    return "\n".join(lines) + "\n"


# Component P(k) definitions: (label, var1, var2)
PK_COMPONENTS = [
    ("tot",   model.Transfer_tot,  model.Transfer_tot),
    ("cdm",   model.Transfer_cdm,  model.Transfer_cdm),
    ("b",     model.Transfer_b,    model.Transfer_b),
    ("cb",    model.Transfer_nonu, model.Transfer_nonu),
    ("cdm_b", model.Transfer_cdm,  model.Transfer_b),
    ("Weyl",  model.Transfer_Weyl, model.Transfer_Weyl),
]
N_PK_COLS = len(PK_COMPONENTS)  # 6


def write_transfer(fname, kh, tdata, rescale_T=1.0, header=""):
    """Write 13-column CAMB transfer function file.

    tdata: shape (13, nk) — from results.get_matter_transfer_data().transfer_data
    Column order: kh, cdm, b, gamma, nu, mass_nu, tot, nonu, totde,
                  Weyl, v_Newt_cdm, v_Newt_b, v_bc
    """
    nk = len(kh)
    with open(fname, 'w') as f:
        if header:
            f.write(header)
        for i in range(nk):
            vals = []
            for j in range(13):
                v = tdata[j, i]
                if j >= 1:  # rescale transfer functions (not k)
                    v *= rescale_T
                vals.append(f"{v:14.6E}")
            f.write("".join(vals) + "\n")


def write_matterpower(fname, kh, pk_cols, header=""):
    """Write multi-column matter power file: k/h  P_tot  P_cdm  P_b  P_cb  P_cdm_b  P_Weyl.

    pk_cols: list of 1-D arrays, one per component.
    """
    ncols = len(pk_cols)
    nk = len(kh)
    with open(fname, 'w') as f:
        if header:
            f.write(header)
        for i in range(nk):
            vals = [f"{kh[i]:14.6E}"]
            for j in range(ncols):
                vals.append(f"{pk_cols[j][i]:14.6E}")
            f.write("".join(vals) + "\n")


# ------------------------------------------------------------------ #
#  Main
# ------------------------------------------------------------------ #

def main():
    ap = argparse.ArgumentParser(
        description="Generate CAMB transfer & power files from namelist")
    ap.add_argument("namelist", help="Fortran namelist file")
    ap.add_argument("-r", "--root", default=None,
                    help="Output root (overrides namelist output_root)")
    ap.add_argument("-g", "--group", default="COSMO_PARAMS",
                    help="Namelist group name (default: COSMO_PARAMS)")
    args = ap.parse_args()

    if not os.path.isfile(args.namelist):
        print(f"Error: {args.namelist} not found"); sys.exit(1)

    nml = parse_namelist(args.namelist, args.group)

    # ---- cosmology ----
    omega_m  = pval(nml.get('omega_m'),  0.3111)
    omega_b  = pval(nml.get('omega_b'),  0.04897)
    omega_l  = pval(nml.get('omega_l'),  0.6889)
    omega_nu = pval(nml.get('omega_nu'), 0.0)
    h0_raw   = pval(nml.get('h0'),       67.36)
    n_s      = pval(nml.get('n_s'),       0.9649)
    sigma8   = pval(nml.get('sigma8'),    0.8111)
    A_s_str  = nml.get('a_s')
    T_cmb    = pval(nml.get('t_cmb'),     2.7255)
    tau      = pval(nml.get('tau'),        0.0544)

    # ---- dark energy ----
    de_model = pval(nml.get('de_model'), 'lambda', dtype=str).lower()
    w0       = pval(nml.get('w0'),       -1.0)
    wa       = pval(nml.get('wa'),        0.0)
    cs2_de   = pval(nml.get('cs2_de'),    1.0)

    # ---- axion EDE parameters ----
    axion_fde_zc  = pval(nml.get('axion_fde_zc'),  0.1)
    axion_zc      = pval(nml.get('axion_zc'),       3000.0)
    axion_w_n     = pval(nml.get('axion_w_n'),      1.0)
    axion_theta_i = pval(nml.get('axion_theta_i'),  1.0)

    # ---- output ----
    redshifts  = parse_redshift_list(nml.get('redshift'))
    root = args.root or pval(nml.get('output_root'), 'camb', dtype=str)

    # ---- derived ----
    if h0_raw <= 10.0:
        h, H0 = h0_raw, h0_raw * 100.0
    else:
        H0, h = h0_raw, h0_raw / 100.0

    omega_k = pval(nml.get('omega_k'), None)
    if omega_k is None:
        omega_k = 1.0 - omega_m - omega_l

    omega_cdm = omega_m - omega_b - omega_nu
    if omega_cdm < 0:
        print(f"Error: omega_cdm = {omega_cdm} < 0"); sys.exit(1)

    ombh2  = omega_b   * h**2
    omch2  = omega_cdm * h**2
    omnuh2 = omega_nu  * h**2

    if omega_nu > 0:
        num_massive_neutrinos = 1
        mnu = omnuh2 * 93.14
        nnu = 3.046
    else:
        num_massive_neutrinos = 0
        mnu = 0.0
        nnu = 3.046

    # ---- print ----
    print("=== mkpower: CAMB Transfer & Power Spectrum Generator ===")
    print(f"  omega_m   = {omega_m}")
    print(f"  omega_b   = {omega_b}")
    print(f"  omega_cdm = {omega_cdm:.6f}")
    print(f"  omega_l   = {omega_l}")
    print(f"  omega_k   = {omega_k:.6e}")
    print(f"  omega_nu  = {omega_nu}")
    print(f"  H0        = {H0} km/s/Mpc  (h = {h})")
    print(f"  de_model  = {de_model}")
    if de_model in ('fluid', 'ppf'):
        print(f"  w0        = {w0}")
        print(f"  wa        = {wa}")
        if de_model == 'fluid':
            print(f"  cs2_de    = {cs2_de}")
    elif de_model == 'axion':
        print(f"  fde_zc    = {axion_fde_zc}")
        print(f"  zc        = {axion_zc}")
        print(f"  w_n       = {axion_w_n}")
        print(f"  theta_i   = {axion_theta_i}")
    print(f"  n_s       = {n_s}")
    if A_s_str is not None:
        print(f"  A_s       = {pval(A_s_str, 0.0)}")
    else:
        print(f"  sigma8    = {sigma8}")
    print(f"  T_cmb     = {T_cmb} K")
    print(f"  tau       = {tau}")
    print(f"  redshifts = {redshifts}")
    print(f"  root      = {root}")
    print()

    # ---- set up CAMB ----
    pars = camb.CAMBparams()

    # Dark energy model
    if de_model == 'lambda':
        pass  # default cosmological constant
    elif de_model == 'fluid':
        de = dark_energy.DarkEnergyFluid(w=w0, wa=wa, cs2=cs2_de)
        pars.DarkEnergy = de
    elif de_model == 'ppf':
        de = dark_energy.DarkEnergyPPF(w=w0, wa=wa)
        pars.DarkEnergy = de
    elif de_model == 'axion':
        de = dark_energy.AxionEffectiveFluid(
            w_n=axion_w_n, fde_zc=axion_fde_zc,
            zc=axion_zc, theta_i=axion_theta_i)
        pars.DarkEnergy = de
    else:
        print(f"Error: unknown de_model '{de_model}'")
        print("  Valid: lambda, fluid, ppf, axion")
        sys.exit(1)

    pars.set_cosmology(
        H0=H0, ombh2=ombh2, omch2=omch2, omk=omega_k,
        tau=tau, TCMB=T_cmb,
        mnu=mnu, num_massive_neutrinos=num_massive_neutrinos, nnu=nnu,
    )
    pars.InitPower.set_params(ns=n_s)

    if A_s_str is not None:
        A_s = pval(A_s_str, 2.1e-9)
        pars.InitPower.set_params(ns=n_s, As=A_s)

    pars.WantTransfer = True
    # Always include z=0 for sigma8 normalization, even if not requested
    camb_redshifts = sorted(set(redshifts) | {0.0}, reverse=True)
    pars.set_matter_power(redshifts=camb_redshifts, kmax=100.0)
    pars.NonLinear = model.NonLinear_none

    # ---- run CAMB ----
    print("Running CAMB...")
    results = camb.get_results(pars)

    # sigma8 rescaling
    if A_s_str is None:
        sigma8_camb = results.get_sigma8_0()
        rescale_pk = (sigma8 / sigma8_camb) ** 2
        rescale_T  = sigma8 / sigma8_camb    # T ~ sqrt(P)
        print(f"  CAMB sigma8 = {sigma8_camb:.6f}, target = {sigma8}")
        print(f"  Rescaling T(k) by {rescale_T:.6f}, P(k) by {rescale_pk:.6f}")
    else:
        rescale_pk = 1.0
        rescale_T  = 1.0
        sigma8_camb = results.get_sigma8_0()
        print(f"  sigma8(z=0) = {sigma8_camb:.6f}")

    # ---- get transfer function data ----
    td = results.get_matter_transfer_data()
    # td.transfer_data shape: (n_var, nq, n_z)
    # n_var = 13 (Transfer_kh=1 .. Transfer_vel_baryon_cdm=13, 0-indexed → 0..12)
    # td.q: wavenumber array (NOT k/h — it's k in 1/Mpc)
    nq = td.nq
    nz_td = td.transfer_data.shape[2]

    # Transfer redshifts (high-z first in CAMB internal order)
    z_transfer = np.array(list(results.transfer_redshifts))

    print(f"  Transfer function: {nq} k-points, {nz_td} redshift(s)")
    print()

    # ---- write files per redshift ----
    # sigma8 per z (CAMB returns high-z first)
    sigma8_all = np.array(results.get_sigma8())
    if A_s_str is None:
        sigma8_all *= np.sqrt(rescale_pk)

    multi_z = (len(redshifts) > 1)
    files_written = []

    # Cosmology info dict for headers
    final_sigma8 = sigma8 if A_s_str is None else sigma8_camb
    cosmo_info = dict(
        omega_m=omega_m, omega_b=omega_b, omega_l=omega_l, h=h,
        n_s=n_s, sigma8=f"{final_sigma8:.6f}", nk=nq, nk_pk=nq,
        de_model=de_model, w0=w0, wa=wa,
    )

    # Only write files for user-requested redshifts (not the auto-added z=0)
    requested_set = set(redshifts)

    for iz_td in range(nz_td):
        z = z_transfer[iz_td]

        # Skip redshifts that were only added for sigma8 normalization
        if not any(abs(z - zr) < 1e-6 for zr in requested_set):
            continue

        # File naming: single-z → <root>_transfer_out.dat
        #              multi-z  → <root>_transfer_out_z<NNN>.dat
        if multi_z:
            ztag = f"_z{z:g}"
            tf_name = f"{root}_transfer_out{ztag}.dat"
            pk_name = f"{root}_matterpower{ztag}.dat"
        else:
            tf_name = f"{root}_transfer_out.dat"
            pk_name = f"{root}_matterpower.dat"

        # Transfer data for this redshift: shape (13, nq)
        tdata = td.transfer_data[:, :, iz_td]
        tf_header = make_transfer_header(z, cosmo_info)
        write_transfer(tf_name, td.q, tdata, rescale_T=rescale_T,
                       header=tf_header)

        # Matter power spectra: compute P(k) for each component
        pk_cols = []
        kh_pk = None
        for label, v1, v2 in PK_COMPONENTS:
            kh_pk_i, z_pk, pk_arr = results.get_matter_power_spectrum(
                minkh=1e-4, maxkh=100.0, npoints=nq, var1=v1, var2=v2)
            if kh_pk is None:
                kh_pk = kh_pk_i
            z_pk = np.array(z_pk)
            ipk = np.argmin(np.abs(z_pk - z))
            pk_cols.append(pk_arr[ipk] * rescale_pk)

        cosmo_info['nk_pk'] = len(kh_pk)
        pk_header = make_pk_header(z, cosmo_info)
        write_matterpower(pk_name, kh_pk, pk_cols, header=pk_header)

        files_written.append(tf_name)
        files_written.append(pk_name)
        ncols_pk = 1 + N_PK_COLS
        print(f"  z = {z:8.3f}  sigma8 = {sigma8_all[iz_td]:.6f}")
        print(f"    -> {tf_name}  ({nq} rows x 13 cols)")
        print(f"    -> {pk_name}  ({len(kh_pk)} rows x {ncols_pk} cols)")

    print(f"\nDone. {len(files_written)} files written.")

    # Print MUSIC config hint
    print(f"\n--- MUSIC configuration hint ---")
    print(f"[cosmology]")
    print(f"Omega_m = {omega_m}")
    print(f"Omega_L = {omega_l}")
    print(f"Omega_b = {omega_b}")
    print(f"H0 = {H0}")
    print(f"sigma_8 = {sigma8 if A_s_str is None else sigma8_camb:.6f}")
    print(f"n_s = {n_s}")
    print(f"transfer = camb_file")
    if multi_z:
        z0_tag = f"_z{redshifts[-1]:g}"
        print(f"transfer_file = {os.path.abspath(root)}_transfer_out{z0_tag}.dat")
    else:
        print(f"transfer_file = {os.path.abspath(root)}_transfer_out.dat")


if __name__ == "__main__":
    main()
